# Run it on windows instead of linux for now for Tasklist testing?
# Could possibly try to get nircmd installed?
os: windows
language: node_js
node_js:
  - "latest"
cache:
  directories:
      - "node-modules"
before_install:
    - choco install nircmd
install:
    - npm install
script:
    - node app.js &
    - env IS_HOME=NO mocha --exit